project_id = "ejxdsuvutluetnaiklmx"

[functions.send-mailing]
verify_jwt = false

[functions.create-admin-account]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false
 
[functions.send-invoice]
verify_jwt = false
 
[functions.create-mollie-payment]
verify_jwt = false
 
[functions.mollie-webhook]
verify_jwt = false

[functions.check-member-email]
verify_jwt = false

[functions.toggle-admin-role]
verify_jwt = false

[functions.send-onboarding-email]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.odata-members]
verify_jwt = false
